
export const countrys = [
  { "name": "Bolivia", "iso_code": "BO1", "code": "591", "flag": "BO" },
  { "name": "Afghanistan", "iso_code": "AF", "code": "93", "flag": "AF" },
  { "name": "Aland Islands", "iso_code": "AX", "code": "358-18", "flag": "AX" },
  { "name": "Albania", "iso_code": "AL", "code": "355", "flag": "AL" },
  { "name": "Algeria", "iso_code": "DZ", "code": "213", "flag": "DZ" },
  { "name": "American Samoa", "iso_code": "AS", "code": "1-684", "flag": "AS" },
  { "name": "Andorra", "iso_code": "AD", "code": "376", "flag": "AD" },
  { "name": "Angola", "iso_code": "AO", "code": "244", "flag": "AO" },
  { "name": "Anguilla", "iso_code": "AI", "code": "1-264", "flag": "AI" },
  { "name": "Antigua and Barbuda", "iso_code": "AG", "code": "1-268", "flag": "AG" },
  { "name": "Argentina", "iso_code": "AR", "code": "54", "flag": "AR" },
  { "name": "Armenia", "iso_code": "AM", "code": "374", "flag": "AM" },
  { "name": "Aruba", "iso_code": "AW", "code": "297", "flag": "AW" },
  { "name": "Australia", "iso_code": "A", "code": "61", "flag": "AU" },
  { "name": "Austria", "iso_code": "AT", "code": "43", "flag": "AT" },
  { "name": "Azerbaijan", "iso_code": "AZ", "code": "994", "flag": "AZ" },
  { "name": "Bahamas", "iso_code": "BS", "code": "1-242", "flag": "BS" },
  { "name": "Bahrain", "iso_code": "BH", "code": "973", "flag": "BH" },
  { "name": "Bangladesh", "iso_code": "BD", "code": "880", "flag": "BD" },
  { "name": "Barbados", "iso_code": "BB", "code": "1-246", "flag": "BB" },
  { "name": "Belarus", "iso_code": "BY", "code": "375", "flag": "BY" },
  { "name": "Belgium", "iso_code": "BE", "code": "32", "flag": "BE" },
  { "name": "Belize", "iso_code": "BZ", "code": "501", "flag": "BZ" },
  { "name": "Benin", "iso_code": "BJ", "code": "229", "flag": "BJ" },
  { "name": "Bermuda", "iso_code": "BM", "code": "1-441", "flag": "BM" },
  { "name": "Bhutan", "iso_code": "BT", "code": "975", "flag": "BT" },
  { "name": "Bosnia and Herzegovina", "iso_code": "BA", "code": "387", "flag": "BA" },
  { "name": "Botswana", "iso_code": "BW", "code": "267", "flag": "BW" },
  { "name": "Brazil", "iso_code": "BR", "code": "55", "flag": "BR" },
  { "name": "British Indian Ocean Territory", "iso_code": "IO", "code": "246", "flag": "IO" },
  { "name": "British Virgin Islands", "iso_code": "VG", "code": "1-284", "flag": "VG" },
  { "name": "Brunei", "iso_code": "BN", "code": "673", "flag": "BN" },
  { "name": "Bolivia", "iso_code": "BO", "code": "591", "flag": "BO" },
  { "name": "Bulgaria", "iso_code": "BG", "code": "359", "flag": "BG" },
  { "name": "Burkina Faso", "iso_code": "BF", "code": "226", "flag": "BF" },
  { "name": "Burundi", "iso_code": "BI", "code": "257", "flag": "BI" },
  { "name": "Cambodia", "iso_code": "KH", "code": "855", "flag": "KH" },
  { "name": "Cameroon", "iso_code": "CM", "code": "237", "flag": "CM" },
  { "name": "Canada", "iso_code": "CA", "code": "1", "flag": "CA" },
  { "name": "Cape Verde", "iso_code": "CV", "code": "238", "flag": "CV" },
  { "name": "Cayman Islands", "iso_code": "KY", "code": "1-345", "flag": "KY" },
  { "name": "Central African Republic", "iso_code": "CF", "code": "236", "flag": "CF" },
  { "name": "Chad", "iso_code": "TD", "code": "235", "flag": "TD" },
  { "name": "Chile", "iso_code": "CL", "code": "56", "flag": "CL" },
  { "name": "China", "iso_code": "CN", "code": "86", "flag": "CN" },
  { "name": "Christmas Island", "iso_code": "CX", "code": "61", "flag": "CX" },
  { "name": "Cocos Islands", "iso_code": "CC", "code": "61", "flag": "CC" },
  { "name": "Comoros", "iso_code": "KM", "code": "269", "flag": "KM" },
  { "name": "Cook Islands", "iso_code": "CK", "code": "682", "flag": "CK" },
  { "name": "Costa Rica", "iso_code": "CR", "code": "506", "flag": "CR" },
  { "name": "Colombia", "iso_code": "CO", "code": "57", "flag": "CO" },
  { "name": "Croatia", "iso_code": "HR", "code": "385", "flag": "HR" },
  { "name": "Cuba", "iso_code": "C", "code": "53", "flag": "CU" },
  { "name": "Cyprus", "iso_code": "CY", "code": "357", "flag": "CY" },
  { "name": "Czech Republic", "iso_code": "CZ", "code": "420", "flag": "CZ" },
  { "name": "Democratic Republic of the Congo", "iso_code": "CD", "code": "243", "flag": "CD" },
  { "name": "Denmark", "iso_code": "DK", "code": "45", "flag": "DK" },
  { "name": "Djibouti", "iso_code": "DJ", "code": "253", "flag": "DJ" },
  { "name": "Dominica", "iso_code": "DM", "code": "1-767", "flag": "DM" },
  { "name": "Russia", "iso_code": "RU", "code": "7", "flag": "RU" },
  { "name": "East Timor", "iso_code": "TL", "code": "670", "flag": "TL" },
  { "name": "Ecuador", "iso_code": "EC", "code": "593", "flag": "EC" },
  { "name": "Egypt", "iso_code": "EG", "code": "20", "flag": "EG" },
  { "name": "El Salvador", "iso_code": "SV", "code": "503", "flag": "SV" },
  { "name": "España", "iso_code": "ES", "code": "34", "flag": "ES" },
  { "name": "Equatorial Guinea", "iso_code": "GQ", "code": "240", "flag": "GQ" },
  { "name": "Eritrea", "iso_code": "ER", "code": "291", "flag": "ER" },
  { "name": "Estados unidos", "iso_code": "US", "code": "1", "flag": "US" },
  { "name": "Estonia", "iso_code": "EE", "code": "372", "flag": "EE" },
  { "name": "Ethiopia", "iso_code": "ET", "code": "251", "flag": "ET" },
  { "name": "Falkland Islands", "iso_code": "FK", "code": "500", "flag": "FK" },
  { "name": "Faroe Islands", "iso_code": "FO", "code": "298", "flag": "FO" },
  { "name": "Fiji", "iso_code": "FJ", "code": "679", "flag": "FJ" },
  { "name": "Finland", "iso_code": "FI", "code": "358", "flag": "FI" },
  { "name": "France", "iso_code": "FR", "code": "33", "flag": "FR" },
  { "name": "French Polynesia", "iso_code": "PF", "code": "689", "flag": "PF" },
  { "name": "Gabon", "iso_code": "GA", "code": "241", "flag": "GA" },
  { "name": "Gambia", "iso_code": "GM", "code": "220", "flag": "GM" },
  { "name": "Georgia", "iso_code": "GE", "code": "995", "flag": "GE" },
  { "name": "Germany", "iso_code": "DE", "code": "49", "flag": "DE" },
  { "name": "Ghana", "iso_code": "GH", "code": "233", "flag": "GH" },
  { "name": "Gibraltar", "iso_code": "GI", "code": "350", "flag": "GI" },
  { "name": "Greece", "iso_code": "GR", "code": "30", "flag": "GR" },
  { "name": "Greenland", "iso_code": "GL", "code": "299", "flag": "GL" },
  { "name": "Grenada", "iso_code": "GD", "code": "1-473", "flag": "GD" },
  { "name": "Guam", "iso_code": "G", "code": "1-671", "flag": "GU" },
  { "name": "Guatemala", "iso_code": "GT", "code": "502", "flag": "GT" },
  { "name": "Guernsey", "iso_code": "GG", "code": "44-1481", "flag": "GG" },
  { "name": "Guinea", "iso_code": "GN", "code": "224", "flag": "GN" },
  { "name": "Guinea-Bissa", "iso_code": "GW", "code": "245", "flag": "GW" },
  { "name": "Guyana", "iso_code": "GY", "code": "592", "flag": "GY" },
  { "name": "Haiti", "iso_code": "HT", "code": "509", "flag": "HT" },
  { "name": "Honduras", "iso_code": "HN", "code": "504", "flag": "HN" },
  { "name": "Hong Kong", "iso_code": "HK", "code": "852", "flag": "HK" },
  { "name": "Hungary", "iso_code": "H", "code": "36", "flag": "HU" },
  { "name": "Iceland", "iso_code": "IS", "code": "354", "flag": "IS" },
  { "name": "India", "iso_code": "IN", "code": "91", "flag": "IN" },
  { "name": "Indonesia", "iso_code": "ID", "code": "62", "flag": "ID" },
  { "name": "Iran", "iso_code": "IR", "code": "98", "flag": "IR" },
  { "name": "Iraq", "iso_code": "IQ", "code": "964", "flag": "IQ" },
  { "name": "Ireland", "iso_code": "IE", "code": "353", "flag": "IE" },
  { "name": "Isle of Man", "iso_code": "IM", "code": "44-1624", "flag": "IM" },
  { "name": "Israel", "iso_code": "IL", "code": "972", "flag": "IL" },
  { "name": "Italy", "iso_code": "IT", "code": "39", "flag": "IT" },
  { "name": "Ivory Coast", "iso_code": "CI", "code": "225", "flag": "CI" },
  { "name": "Jamaica", "iso_code": "JM", "code": "1-876", "flag": "JM" },
  { "name": "Japan", "iso_code": "JP", "code": "81", "flag": "JP" },
  { "name": "Jersey", "iso_code": "JE", "code": "44-1534", "flag": "JE" },
  { "name": "Jordan", "iso_code": "JO", "code": "962", "flag": "JO" },
  { "name": "Kazakhstan", "iso_code": "KZ", "code": "7", "flag": "KZ" },
  { "name": "Kenya", "iso_code": "KE", "code": "254", "flag": "KE" },
  { "name": "Kiribati", "iso_code": "KI", "code": "686", "flag": "KI" },
  { "name": "Kuwait", "iso_code": "KW", "code": "965", "flag": "KW" },
  { "name": "Kyrgyzstan", "iso_code": "KG", "code": "996", "flag": "KG" },
  { "name": "Laos", "iso_code": "LA", "code": "856", "flag": "LA" },
  { "name": "Latvia", "iso_code": "LV", "code": "371", "flag": "LV" },
  { "name": "Lebanon", "iso_code": "LB", "code": "961", "flag": "LB" },
  { "name": "Lesotho", "iso_code": "LS", "code": "266", "flag": "LS" },
  { "name": "Liberia", "iso_code": "LR", "code": "231", "flag": "LR" },
  { "name": "Libya", "iso_code": "LY", "code": "218", "flag": "LY" },
  { "name": "Liechtenstein", "iso_code": "LI", "code": "423", "flag": "LI" },
  { "name": "Lithuania", "iso_code": "LT", "code": "370", "flag": "LT" },
  { "name": "Luxembourg", "iso_code": "L", "code": "352", "flag": "LU" },
  { "name": "Macao", "iso_code": "MO", "code": "853", "flag": "MO" },
  { "name": "Macedonia", "iso_code": "MK", "code": "389", "flag": "MK" },
  { "name": "Madagascar", "iso_code": "MG", "code": "261", "flag": "MG" },
  { "name": "Malawi", "iso_code": "MW", "code": "265", "flag": "MW" },
  { "name": "Malaysia", "iso_code": "MY", "code": "60", "flag": "MY" },
  { "name": "Maldives", "iso_code": "MV", "code": "960", "flag": "MV" },
  { "name": "Mali", "iso_code": "ML", "code": "223", "flag": "ML" },
  { "name": "Malta", "iso_code": "MT", "code": "356", "flag": "MT" },
  { "name": "Marshall Islands", "iso_code": "MH", "code": "692", "flag": "MH" },
  { "name": "Martinique", "iso_code": "MQ", "code": "596", "flag": "MQ" },
  { "name": "Mauritania", "iso_code": "MR", "code": "222", "flag": "MR" },
  { "name": "Mauritius", "iso_code": "M", "code": "230", "flag": "MU" },
  { "name": "Mayotte", "iso_code": "YT", "code": "262", "flag": "YT" },
  { "name": "Mexico", "iso_code": "MX", "code": "52", "flag": "MX" },
  { "name": "Micronesia", "iso_code": "FM", "code": "691", "flag": "FM" },
  { "name": "Moldova", "iso_code": "MD", "code": "373", "flag": "MD" },
  { "name": "Monaco", "iso_code": "MC", "code": "377", "flag": "MC" },
  { "name": "Mongolia", "iso_code": "MN", "code": "976", "flag": "MN" },
  { "name": "Montenegro", "iso_code": "ME", "code": "382", "flag": "ME" },
  { "name": "Montserrat", "iso_code": "MS", "code": "1-664", "flag": "MS" },
  { "name": "Morocco", "iso_code": "MA", "code": "212", "flag": "MA" },
  { "name": "Mozambique", "iso_code": "MZ", "code": "258", "flag": "MZ" },
  { "name": "Myanmar", "iso_code": "MM", "code": "95", "flag": "MM" },
  { "name": "Namibia", "iso_code": "NA", "code": "264", "flag": "NA" },
  { "name": "Naur", "iso_code": "NR", "code": "674", "flag": "NR" },
  { "name": "Nepal", "iso_code": "NP", "code": "977", "flag": "NP" },
  { "name": "Netherlands", "iso_code": "NL", "code": "31", "flag": "NL" },
  { "name": "New Caledonia", "iso_code": "NC", "code": "687", "flag": "NC" },
  { "name": "New Zealand", "iso_code": "NZ", "code": "64", "flag": "NZ" },
  { "name": "Nicaragua", "iso_code": "NI", "code": "505", "flag": "NI" },
  { "name": "Niger", "iso_code": "NE", "code": "227", "flag": "NE" },
  { "name": "Nigeria", "iso_code": "NG", "code": "234", "flag": "NG" },
  { "name": "Niue", "iso_code": "N", "code": "683", "flag": "NU" },
  { "name": "Norfolk Island", "iso_code": "NF", "code": "672", "flag": "NF" },
  { "name": "North Korea", "iso_code": "KP", "code": "850", "flag": "KP" },
  { "name": "Northern Mariana Islands", "iso_code": "MP", "code": "1-670", "flag": "MP" },
  { "name": "Norway", "iso_code": "NO", "code": "47", "flag": "NO" },
  { "name": "Oman", "iso_code": "OM", "code": "968", "flag": "OM" },
  { "name": "Pakistan", "iso_code": "PK", "code": "92", "flag": "PK" },
  { "name": "Pala", "iso_code": "PW", "code": "680", "flag": "PW" },
  { "name": "Palestinian Territory", "iso_code": "PS", "code": "970", "flag": "PS" },
  { "name": "Panama", "iso_code": "PA", "code": "507", "flag": "PA" },
  { "name": "Papua New Guinea", "iso_code": "PG", "code": "675", "flag": "PG" },
  { "name": "Paraguay", "iso_code": "PY", "code": "595", "flag": "PY" },
  { "name": "Per\u00fa", "iso_code": "PE", "code": "51", "flag": "PE" },
  { "name": "Philippines", "iso_code": "PH", "code": "63", "flag": "PH" },
  { "name": "Pitcairn", "iso_code": "PN", "code": "870", "flag": "PN" },
  { "name": "Poland", "iso_code": "PL", "code": "48", "flag": "PL" },
  { "name": "Portugal", "iso_code": "PT", "code": "351", "flag": "PT" },
  { "name": "Puerto Rico", "iso_code": "PR", "code": "1-787", "flag": "PR" },
  { "name": "Puerto Rico", "iso_code": "PR1", "code": "1-939", "flag": "PR" },
  { "name": "Qatar", "iso_code": "QA", "code": "974", "flag": "QA" },
  { "name": "Republic of the Congo", "iso_code": "CG", "code": "242", "flag": "CG" },
  { "name": "Romania", "iso_code": "RO", "code": "40", "flag": "RO" },
  { "name": "Rwanda", "iso_code": "RW", "code": "250", "flag": "RW" },
  { "name": "Saint Barthelemy", "iso_code": "BL", "code": "590", "flag": "BL" },
  { "name": "Saint Helena", "iso_code": "SH", "code": "290", "flag": "SH" },
  { "name": "Saint Kitts and Nevis", "iso_code": "KN", "code": "1-869", "flag": "KN" },
  { "name": "Saint Lucia", "iso_code": "LC", "code": "1-758", "flag": "LC" },
  { "name": "Saint Martin", "iso_code": "MF", "code": "590", "flag": "MF" },
  { "name": "Saint Pierre and Miquelon", "iso_code": "PM", "code": "508", "flag": "PM" },
  { "name": "Saint Vincent and the Grenadines", "iso_code": "VC", "code": "1-784", "flag": "VC" },
  { "name": "Samoa", "iso_code": "WS", "code": "685", "flag": "WS" },
  { "name": "San Marino", "iso_code": "SM", "code": "378", "flag": "SM" },
  { "name": "Sao Tome and Principe", "iso_code": "ST", "code": "239", "flag": "ST" },
  { "name": "Saudi Arabia", "iso_code": "SA", "code": "966", "flag": "SA" },
  { "name": "Senegal", "iso_code": "SN", "code": "221", "flag": "SN" },
  { "name": "Serbia", "iso_code": "RS", "code": "381", "flag": "RS" },
  { "name": "Seychelles", "iso_code": "SC", "code": "248", "flag": "SC" },
  { "name": "Sierra Leone", "iso_code": "SL", "code": "232", "flag": "SL" },
  { "name": "Singapore", "iso_code": "SG", "code": "65", "flag": "SG" },
  { "name": "Sint Maarten", "iso_code": "SX", "code": "599", "flag": "SX" },
  { "name": "Slovakia", "iso_code": "SK", "code": "421", "flag": "SK" },
  { "name": "Slovenia", "iso_code": "SI", "code": "386", "flag": "SI" },
  { "name": "Solomon Islands", "iso_code": "SB", "code": "677", "flag": "SB" },
  { "name": "Somalia", "iso_code": "SO", "code": "252", "flag": "SO" },
  { "name": "South Africa", "iso_code": "ZA", "code": "27", "flag": "ZA" },
  { "name": "South Korea", "iso_code": "KR", "code": "82", "flag": "KR" },
  { "name": "Sri Lanka", "iso_code": "LK", "code": "94", "flag": "LK" },
  { "name": "Sudan", "iso_code": "SD", "code": "249", "flag": "SD" },
  { "name": "Suriname", "iso_code": "SR", "code": "597", "flag": "SR" },
  { "name": "Svalbard and Jan Mayen", "iso_code": "SJ", "code": "47", "flag": "SJ" },
  { "name": "Swaziland", "iso_code": "SZ", "code": "268", "flag": "SZ" },
  { "name": "Sweden", "iso_code": "SE", "code": "46", "flag": "SE" },
  { "name": "Switzerland", "iso_code": "CH", "code": "41", "flag": "CH" },
  { "name": "Syria", "iso_code": "SY", "code": "963", "flag": "SY" },
  { "name": "Taiwan", "iso_code": "TW", "code": "886", "flag": "TW" },
  { "name": "Tajikistan", "iso_code": "TJ", "code": "992", "flag": "TJ" },
  { "name": "Tanzania", "iso_code": "TZ", "code": "255", "flag": "TZ" },
  { "name": "Thailand", "iso_code": "TH", "code": "66", "flag": "TH" },
  { "name": "Togo", "iso_code": "TG", "code": "228", "flag": "TG" },
  { "name": "Tokela", "iso_code": "TK", "code": "690", "flag": "TK" },
  { "name": "Tonga", "iso_code": "TO", "code": "676", "flag": "TO" },
  { "name": "Trinidad and Tobago", "iso_code": "TT", "code": "1-868", "flag": "TT" },
  { "name": "Tunisia", "iso_code": "TN", "code": "216", "flag": "TN" },
  { "name": "Turkey", "iso_code": "TR", "code": "90", "flag": "TR" },
  { "name": "Turkmenistan", "iso_code": "TM", "code": "993", "flag": "TM" },
  { "name": "Turks and Caicos Islands", "iso_code": "TC", "code": "1-649", "flag": "TC" },
  { "name": "Tuval", "iso_code": "TV", "code": "688", "flag": "TV" },
  { "name": "U.S. Virgin Islands", "iso_code": "VI", "code": "1-340", "flag": "VI" },
  { "name": "Uganda", "iso_code": "UG", "code": "256", "flag": "UG" },
  { "name": "Ukraine", "iso_code": "UA", "code": "380", "flag": "UA" },
  { "name": "United Arab Emirates", "iso_code": "AE", "code": "971", "flag": "AE" },
  { "name": "United Kingdom", "iso_code": "GB", "code": "44", "flag": "GB" },
  { "name": "Uruguay", "iso_code": "UY", "code": "598", "flag": "UY" },
  { "name": "Uzbekistan", "iso_code": "UZ", "code": "998", "flag": "UZ" },
  { "name": "Vatican", "iso_code": "VA", "code": "379", "flag": "VA" },
  { "name": "Venezuela", "iso_code": "VE", "code": "58", "flag": "VE" },
  { "name": "Vietnam", "iso_code": "VN", "code": "84", "flag": "VN" },
  { "name": "Wallis and Futuna", "iso_code": "WF", "code": "681", "flag": "WF" },
  { "name": "Western Sahara", "iso_code": "EH", "code": "212", "flag": "EH" },
  { "name": "Yemen", "iso_code": "YE", "code": "967", "flag": "YE" },
  { "name": "Zambia", "iso_code": "ZM", "code": "260", "flag": "ZM" },
  { "name": "Zimbabwe", "iso_code": "ZW", "code": "263", "flag": "ZW" },
  { "name": "Curazao", "iso_code": "CW", "code": "5999", "flag": "CW" },
  { "name": "Bolivia", "iso_code": "BO2", "code": "591", "flag": "BO" },
];